Use shutil.move instead of os.rename
os.rename only works if source and destination are on the same file system.
Otherwise it throws the error:
	OSError: [Errno 18] Invalid cross-device link